<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\District;
use App\Models\Project;
use App\Models\TimelineMilestone;
use App\Models\CitizenTestimonial;
use App\Models\KeralaStateInfo;
use App\Models\ChiefMinister;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Seed default Admin User
        User::updateOrCreate(
            ['email' => 'admin@janavikasam.gov.in'],
            [
                'name' => 'Administrator',
                'password' => Hash::make('password'),
                'is_admin' => true,
            ]
        );

        // 2. Seed Districts
        $districts = [
            [
                'id' => 'kasaragod',
                'name_en' => 'Kasaragod',
                'name_ml' => 'കാസർഗോഡ്',
                'investment' => '₹340 Cr',
                'projects_count' => 8,
                'highlight_ml' => 'മലയോര ഹൈവേ ഒന്നാം ഘട്ടം പൂർത്തിയായി',
                'highlight_en' => 'Hill Highway Phase 1 Completed',
                'x' => 80,
                'y' => 80,
            ],
            [
                'id' => 'kannur',
                'name_en' => 'Kannur',
                'name_ml' => 'കണ്ണൂർ',
                'investment' => '₹820 Cr',
                'projects_count' => 15,
                'highlight_ml' => 'അന്താരാഷ്ട്ര നിലവാരമുള്ള നഗര പാതകൾ',
                'highlight_en' => 'International Standard City Roads',
                'x' => 100,
                'y' => 140,
            ],
            [
                'id' => 'wayanad',
                'name_en' => 'Wayanad',
                'name_ml' => 'വയനാട്',
                'investment' => '₹290 Cr',
                'projects_count' => 6,
                'highlight_ml' => 'തുരങ്കപ്പാത നിർമാണത്തിന്റെ തുടക്കം',
                'highlight_en' => 'Anakkampoyil-Meppadi Tunnel Road Init',
                'x' => 160,
                'y' => 160,
            ],
            [
                'id' => 'kozhikode',
                'name_en' => 'Kozhikode',
                'name_ml' => 'കോഴിക്കോട്',
                'investment' => '₹710 Cr',
                'projects_count' => 12,
                'highlight_ml' => 'കോഴിക്കോട് ബൈപാസ് 6 വരി പാതയായി വികസിപ്പിച്ചു',
                'highlight_en' => 'Kozhikode Bypass 6-Lane Upgrade',
                'x' => 120,
                'y' => 200,
            ],
            [
                'id' => 'malappuram',
                'name_en' => 'Malappuram',
                'name_ml' => 'മലപ്പുറം',
                'investment' => '₹650 Cr',
                'projects_count' => 11,
                'highlight_ml' => 'ദേശീയപാത 66 വികസനം ദ്രുതഗതിയിൽ',
                'highlight_en' => 'NH 66 Expansion Running Smoothly',
                'x' => 160,
                'y' => 240,
            ],
            [
                'id' => 'palakkad',
                'name_en' => 'Palakkad',
                'name_ml' => 'പാലക്കാട്',
                'investment' => '₹520 Cr',
                'projects_count' => 10,
                'highlight_ml' => 'വ്യവസായ പാർക്ക് വികസനം',
                'highlight_en' => 'Palakkad Mega Food Park & Industrial Corridor',
                'x' => 210,
                'y' => 260,
            ],
            [
                'id' => 'thrissur',
                'name_en' => 'Thrissur',
                'name_ml' => 'തൃശ്ശൂർ',
                'investment' => '₹680 Cr',
                'projects_count' => 14,
                'highlight_ml' => 'ശക്തൻ മാർക്കറ്റ് സ്മാർട്ട് നവീകരണം',
                'highlight_en' => 'Sakthan Market Smart Modernization',
                'x' => 170,
                'y' => 310,
            ],
            [
                'id' => 'ernakulam',
                'name_en' => 'Ernakulam',
                'name_ml' => 'എറണാകുളം',
                'investment' => '₹1,850 Cr',
                'projects_count' => 22,
                'highlight_ml' => 'കൊച്ചി വാട്ടർ മെട്രോ പുതിയ ടെർമിനലുകൾ',
                'highlight_en' => 'Kochi Water Metro Expansion',
                'x' => 170,
                'y' => 370,
            ],
            [
                'id' => 'idukki',
                'name_en' => 'Idukki',
                'name_ml' => 'ഇടുക്കി',
                'investment' => '₹410 Cr',
                'projects_count' => 9,
                'highlight_ml' => 'മൂന്നാർ റോഡ് വികസന പദ്ധതി',
                'highlight_en' => 'Munnar Scenic Highway Redevelopment',
                'x' => 240,
                'y' => 390,
            ],
            [
                'id' => 'kottayam',
                'name_en' => 'Kottayam',
                'name_ml' => 'കോട്ടയം',
                'investment' => '₹480 Cr',
                'projects_count' => 11,
                'highlight_ml' => 'റബ്ബർ പാർക്ക് വികസന പ്രവർത്തനങ്ങൾ',
                'highlight_en' => 'Kottayam Rubber Park Expansion',
                'x' => 200,
                'y' => 430,
            ],
            [
                'id' => 'alappuzha',
                'name_en' => 'Alappuzha',
                'name_ml' => 'ആലപ്പുഴ',
                'investment' => '₹590 Cr',
                'projects_count' => 12,
                'highlight_ml' => 'ആലപ്പുഴ ബൈപാസ് സ്മാർട്ട് ലൈറ്റിംഗ്',
                'highlight_en' => 'Alappuzha Bypass Smart LED & Beautification',
                'x' => 170,
                'y' => 460,
            ],
            [
                'id' => 'pathanamthitta',
                'name_en' => 'Pathanamthitta',
                'name_ml' => 'പത്തനംതിട്ട',
                'investment' => '₹310 Cr',
                'projects_count' => 7,
                'highlight_ml' => 'ശബരിമല റോഡുകളുടെ അത്യാധുനിക ടാറിങ്',
                'highlight_en' => 'Sabarimala Roads BM&BC Tarring',
                'x' => 220,
                'y' => 490,
            ],
            [
                'id' => 'kollam',
                'name_en' => 'Kollam',
                'name_ml' => 'കൊല്ലം',
                'investment' => '₹620 Cr',
                'projects_count' => 13,
                'highlight_ml' => 'കൊല്ലം തുറമുഖം നവീകരണം',
                'highlight_en' => 'Kollam Port Infrastructure Upgrade',
                'x' => 200,
                'y' => 530,
            ],
            [
                'id' => 'trivandrum',
                'name_en' => 'Thiruvananthapuram',
                'name_ml' => 'തിരുവനന്തപുരം',
                'investment' => '₹1,450 Cr',
                'projects_count' => 20,
                'highlight_ml' => 'ഡിജിറ്റൽ സയൻസ് പാർക്ക് നിർമ്മാണം',
                'highlight_en' => 'Digital Science Park Execution',
                'x' => 230,
                'y' => 590,
            ],
        ];

        foreach ($districts as $d) {
            District::updateOrCreate(['id' => $d['id']], $d);
        }

        // 3. Seed Projects
        $projects = [
            [
                'id' => 'kochi-biennale',
                'category_ml' => 'കലയും വിനോദസഞ്ചാരവും',
                'category_en' => 'Art & Tourism',
                'title_ml' => 'കൊച്ചി-മുസിരിസ് ബിനാലെ തുടക്കം',
                'title_en' => 'Kochi-Muziris Biennale Launch',
                'district_ml' => 'എറണാകുളം',
                'district_en' => 'Ernakulam',
                'description_ml' => 'കേരളത്തെ ആഗോള സാംസ്കാരിക ഭൂപടത്തിൽ അടയാളപ്പെടുത്തിക്കൊണ്ട് കൊച്ചിയിൽ ഇന്ത്യയിലെ ആദ്യത്തെ അന്താരാഷ്ട്ര സമകാലിക കലാപ്രദർശനം ആരംഭിച്ചു.',
                'description_en' => 'Establishing India\'s first international contemporary art exhibition in Kochi, placing Kerala on the global cultural map.',
                'investment' => '₹75 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2011): ഫോർട്ട് കൊച്ചിയിൽ അന്താരാഷ്ട്ര നിലവാരത്തിലുള്ള കലാ സാംസ്കാരിക വേദി ഒരുക്കൽ.',
                'before_text_en' => 'Promise (2011): Support for creating an international cultural platform in historic Fort Kochi.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2012): ഒന്നാം പതിപ്പ് വൻ വിജയമായി പൂർത്തിയായി, നാല് ലക്ഷത്തിലധികം സന്ദർശകർ പങ്കെടുത്തു.',
                'after_text_en' => 'Reality (2012): Inaugural edition hosted, attracting over 400,000 global art lovers.',
                'before_img' => 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
                'year' => '2012',
                'government_en' => 'UDF Government (Oommen Chandy)',
                'government_ml' => 'യു.ഡി.എഫ്. സർക്കാർ (ഉമ്മൻ ചാണ്ടി)',
            ],
            [
                'id' => 'kochi-metro-p1',
                'category_ml' => 'മെട്രോ റെയിൽ',
                'category_en' => 'Transit Infrastructure',
                'title_ml' => 'കൊച്ചി മെട്രോ ഒന്നാം ഘട്ടം നിർമ്മാണം',
                'title_en' => 'Kochi Metro Phase 1 Construction',
                'district_ml' => 'എറണാകുളം',
                'district_en' => 'Ernakulam',
                'description_ml' => 'കൊച്ചി നഗരത്തിലെ ഗതാഗതക്കുരുക്ക് കുറയ്ക്കുന്നതിനായി ആലുവ മുതൽ പേട്ട വരെയുള്ള കൊച്ചി മെട്രോ ഒന്നാം ഘട്ടത്തിന്റെ നിർമ്മാണം.',
                'description_en' => 'Commencement and major construction of Kochi Metro Phase 1 spanning from Aluva to Pettah, resolving urban traffic bottlenecks.',
                'investment' => '₹5,180 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2011): നഗരത്തെയും സബർബൻ മേഖലകളെയും ബന്ധിപ്പിക്കുന്ന മെട്രോ റെയിൽ പദ്ധതി.',
                'before_text_en' => 'Promise (2011): Conceived mass rapid transit system to connect suburban areas with city hub.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2016): പ്രധാന ട്രാക്കുകൾ, സ്റ്റേഷനുകൾ എന്നിവയുടെ പണി പൂർത്തിയാക്കി ട്രയൽ റൺ നടത്തി.',
                'after_text_en' => 'Reality (2016): Completion of major track works, stations structure, and test runs.',
                'before_img' => 'https://images.unsplash.com/photo-1568971305891-b3b4f5df3141?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1549497538-3012254157b2?auto=format&fit=crop&w=800&q=80',
                'year' => '2013',
                'government_en' => 'UDF Government (Oommen Chandy)',
                'government_ml' => 'യു.ഡി.എഫ്. സർക്കാർ (ഉമ്മൻ ചാണ്ടി)',
            ],
            [
                'id' => 'hospital-upgrade',
                'category_ml' => 'ആരോഗ്യ മേഖല',
                'category_en' => 'Healthcare',
                'title_ml' => 'കണ്ണൂർ മെഡിക്കൽ കോളേജ് സൂപ്പർ സ്പെഷ്യാലിറ്റി',
                'title_en' => 'Kannur Medical College Super Specialty Wing',
                'district_ml' => 'കണ്ണൂർ',
                'district_en' => 'Kannur',
                'description_ml' => 'ഉത്തര മലബാറിന് ആശ്വാസമായി അത്യാധുനിക മെഡിക്കൽ സൗകര്യങ്ങളും ഓങ്കോളജി ബ്ലോക്കുകളും സജ്ജീകരിച്ച ഹോസ്പിറ്റൽ.',
                'description_en' => 'Highly advanced medical wing with oncology, cardiology, and state-of-the-art trauma care for North Malabar.',
                'investment' => '₹450 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2016): അടിസ്ഥാന കിടക്ക സൗകര്യങ്ങളുടെ കുറവ്, സൂപ്പർ സ്പെഷ്യാലിറ്റി ചികിത്സയ്ക്ക് ദൂരയാത്ര.',
                'before_text_en' => 'Promise (2016): Understaffed facilities, lack of advanced trauma care forcing travel to neighboring states.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2019): 800+ കിടക്കകൾ, ലോകോത്തര ഓപ്പറേഷൻ തിയേറ്ററുകൾ, കാർഡിയാക് കെയർ യൂണിറ്റ്.',
                'after_text_en' => 'Reality (2019): World-class 800-bed facility, advanced robotic surgeries, and free cardiology services.',
                'before_img' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
                'year' => '2019',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
            ],
            [
                'id' => 'bridge-const',
                'category_ml' => 'പാലങ്ങൾ',
                'category_en' => 'Bridges',
                'title_ml' => 'കോഴിക്കോട് ബൈപാസ് മാതൃകാ പാലങ്ങൾ',
                'title_en' => 'Kozhikode Bypass Bridge Mega Project',
                'district_ml' => 'കോഴിക്കോട്',
                'district_en' => 'Kozhikode',
                'description_ml' => 'യാത്രാസമയം മൂന്നിലൊന്നായി കുറയ്ക്കുന്ന കോഴിക്കോട് ബൈപാസിലെ 6 വരി പാലങ്ങളുടെ നിർമ്മാണം.',
                'description_en' => 'Construction of massive 6-lane bridges along the Kozhikode bypass to reduce traffic congestion.',
                'investment' => '₹1,200 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2016): പഴയ ഇടുങ്ങിയ പാലം, മണിക്കൂറുകൾ നീളുന്ന ബ്ലോക്ക്.',
                'before_text_en' => 'Promise (2016): Aging narrow single-lane bridge, causing hours of gridlock daily.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2020): നദിക്ക് കുറുകെ 6 വരികളിൽ അത്യാധുനിക കേബിൾ കണക്റ്റഡ് പാലം.',
                'after_text_en' => 'Reality (2020): Brand new state-of-the-art 6-lane concrete bridge spanning the river.',
                'before_img' => 'https://images.unsplash.com/photo-1590480397854-3fa3487fe1ca?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1545624446-424e6c43d915?auto=format&fit=crop&w=800&q=80',
                'year' => '2020',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
            ],
            [
                'id' => 'water-metro',
                'category_ml' => 'ഗതാഗതം / നവീകരണം',
                'category_en' => 'Urban Infrastructure',
                'title_ml' => 'കൊച്ചി വാട്ടർ മെട്രോ നെറ്റ്വർക്ക്',
                'title_en' => 'Kochi Water Metro Network',
                'district_ml' => 'എറണാകുളം',
                'district_en' => 'Ernakulam',
                'description_ml' => 'കൊച്ചിയിലെ ദ്വീപുകളെ തമ്മിൽ ബന്ധിപ്പിക്കുന്ന ഏഷ്യയിലെ ആദ്യത്തെ സംയോജിത വാട്ടർ മെട്രോ ഗതാഗത സംവിധാനം.',
                'description_en' => 'Asia\'s first integrated water metro transportation system connecting 10 islands around Kochi.',
                'investment' => '₹1,137 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2021): ആശ്രയമറ്റ പഴയ ബോട്ട് സർവീസുകൾ, സുരക്ഷാ ആശങ്കകൾ.',
                'before_text_en' => 'Promise (2021): Unreliable, noisy wooden boats with high emissions and safety hazards.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2023): വൈഫൈ സൗകര്യമുള്ള പരിസ്ഥിതി സൗഹൃദ എയർ കണ്ടീഷൻഡ് ഹൈബ്രിഡ് ഇലക്ട്രിക് കപ്പലുകൾ.',
                'after_text_en' => 'Reality (2023): Eco-friendly air-conditioned electric hybrid ferries with automated ticketing and fast wifi.',
                'before_img' => 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80',
                'year' => '2023',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
            ],
            [
                'id' => 'school-mod',
                'category_ml' => 'പൊതുവിദ്യാഭ്യാസം',
                'category_en' => 'Education',
                'title_ml' => 'ഹൈടെക് സ്മാർട്ട് ക്ലാസ്സ്റൂം പദ്ധതി',
                'title_en' => 'Hi-Tech Government School Modernization',
                'district_ml' => 'എല്ലാ ജില്ലകളിലും',
                'district_en' => 'All Districts',
                'description_ml' => 'പൊതുവിദ്യാലയങ്ങളെ അന്താരാഷ്ട്ര നിലവാരത്തിലേക്ക് ഉയർത്തി സ്മാർട്ട് ക്ലാസ് റൂമുകളും ആധുനിക ലാബുകളും ഒരുക്കി.',
                'description_en' => 'Upgrading public schools to international standards with digital smartboards, science labs, and sports grounds.',
                'investment' => '₹850 Cr',
                'percentage' => 100,
                'before_text_ml' => 'വാഗ്ദാനം (2021): ചോർന്നൊലിക്കുന്ന കെട്ടിടങ്ങൾ, പഴയ ബ്ലാക്ക് ബോർഡുകൾ.',
                'before_text_en' => 'Promise (2021): Leaking classrooms, outdated blackboards, lack of computers or laboratory devices.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2024): സ്മാർട്ട് പ്രൊജക്റ്ററുകൾ, റോബോട്ടിക് ലാബുകൾ, അത്യാധുനിക കായിക സൗകര്യങ്ങൾ.',
                'after_text_en' => 'Reality (2024): Fully air-conditioned digital smart classes, robotic labs, and turf playing fields.',
                'before_img' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=800&q=80',
                'year' => '2024',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
            ],
            [
                'id' => 'road-dev',
                'category_ml' => 'റോഡ് വികസനം',
                'category_en' => 'Road Development',
                'title_ml' => 'ദേശീയപാത 66 വികസനം (NH-66)',
                'title_en' => 'National Highway 66 Six-Lane Expansion',
                'district_ml' => 'കാസർഗോഡ് മുതൽ തിരുവനന്തപുരം വരെ',
                'district_en' => 'Kasaragod to Thiruvananthapuram',
                'description_ml' => 'കേരളത്തിന്റെ വടക്കേ അറ്റം മുതൽ തെക്കേ അറ്റം വരെയുള്ള യാത്ര സുഗമമാക്കുന്ന 6 വരി അന്താരാഷ്ട്ര ഹൈവേ നിർമ്മാണം.',
                'description_en' => 'Construction of a 6-lane international standard highway connecting the northernmost and southernmost tips of Kerala.',
                'investment' => '₹25,000 Cr+',
                'percentage' => 95,
                'before_text_ml' => 'വാഗ്ദാനം (2021): ഇടുങ്ങിയ 2-വരി പാതകൾ, കനത്ത ഗതാഗതക്കുരുക്ക്, വർദ്ധിച്ച യാത്രാസമയം.',
                'before_text_en' => 'Promise (2021): Narrow 2-lane roads, heavy traffic congestion, high travel times.',
                'after_text_ml' => 'യാഥാർത്ഥ്യം (2025): സുരക്ഷിതമായ 6-വരി റൺവേ, ആധുനിക സർവീസ് റോഡുകൾ, ഫ്ലൈ ഓവറുകൾ, കുറഞ്ഞ യാത്രാസമയം.',
                'after_text_en' => 'Reality (2025): Safe 6-lane bypasses, modern service roads, high-speed flyovers, drastically cut travel times.',
                'before_img' => 'https://images.unsplash.com/photo-1599740831114-57aa8705309f?auto=format&fit=crop&w=800&q=80',
                'after_img' => 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=800&q=80',
                'year' => '2025',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
            ],
        ];

        foreach ($projects as $p) {
            Project::updateOrCreate(['id' => $p['id']], $p);
        }

        // 4. Seed TimelineMilestones
        $milestones = [
            [
                'year' => '2012',
                'phase_ml' => 'ബിനാലെ തുടക്കം',
                'phase_en' => 'Biennale Inauguration',
                'desc_ml' => 'ആഗോള സമകാലിക കല പ്രദർശിപ്പിക്കുന്ന കൊച്ചി-മുസിരിസ് ബിനാലെ സംസ്ഥാന സർക്കാരിന്റെ പിന്തുണയോടെ ആരംഭിച്ചു.',
                'desc_en' => 'Kochi-Muziris Biennale launched under patronage of the state government, showcasing global contemporary art.',
                'government_en' => 'UDF Government (Oommen Chandy)',
                'government_ml' => 'യു.ഡി.എഫ്. സർക്കാർ (ഉമ്മൻ ചാണ്ടി)',
                'stats_en' => 'First contemporary art biennale in South Asia',
                'stats_ml' => 'ദക്ഷിണേഷ്യയിലെ ആദ്യ സമകാലിക കലാപ്രദർശനം',
                'icon' => 'award',
            ],
            [
                'year' => '2013',
                'phase_ml' => 'മെട്രോ നിർമ്മാണം',
                'phase_en' => 'Metro Infrastructure',
                'desc_ml' => 'കൊച്ചി മെട്രോ പദ്ധതിയുടെ ആദ്യഘട്ട നിർമ്മാണ ജോലികളും പൈലിംഗും കൊച്ചിയിൽ വേഗത്തിലാക്കി.',
                'desc_en' => 'Piling works and viaduct construction for Kochi Metro Phase 1 fast-tracked across Kochi city corridors.',
                'government_en' => 'UDF Government (Oommen Chandy)',
                'government_ml' => 'യു.ഡി.എഫ്. സർക്കാർ (ഉമ്മൻ ചാണ്ടി)',
                'stats_en' => '₹5,180 Cr investment approved',
                'stats_ml' => '₹5,180 കോടിയുടെ പദ്ധതി അനുമതി',
                'icon' => 'hardhat',
            ],
            [
                'year' => '2015',
                'phase_ml' => 'വിഴിഞ്ഞം തുറമുഖ കരാർ',
                'phase_en' => 'Vizhinjam Seaport Pact',
                'desc_ml' => 'വിഴിഞ്ഞം അന്താരാഷ്ട്ര തുറമുഖ പദ്ധതിക്കായി കരാർ ഒപ്പിടുകയും ആദ്യഘട്ട നിർമ്മാണം ആരംഭിക്കുകയും ചെയ്തു.',
                'desc_en' => 'Concession agreement signed for Vizhinjam International Transshipment Deepwater Seaport and construction initiated.',
                'government_en' => 'UDF Government (Oommen Chandy)',
                'government_ml' => 'യു.ഡി.എഫ്. സർക്കാർ (ഉമ്മൻ ചാണ്ടി)',
                'stats_en' => 'Concession Agreement Signed',
                'stats_ml' => 'തുറമുഖ കരാർ ഒപ്പുവെച്ചു',
                'icon' => 'landmark',
            ],
            [
                'year' => '2017',
                'phase_ml' => 'കൊച്ചി മെട്രോ സമർപ്പണം',
                'phase_en' => 'Kochi Metro Commissioning',
                'desc_ml' => 'കൊച്ചി മെട്രോ ഒന്നാം ഘട്ടം നിർമ്മാണം പൂർത്തിയാക്കി ആലുവ മുതൽ പാലാരിവട്ടം വരെയുള്ള സർവീസിന് തുറന്നുകൊടുത്തു.',
                'desc_en' => 'Kochi Metro Phase 1 completed and commissioned for commercial service from Aluva to Palarivattom.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => 'First metro network in Kerala',
                'stats_ml' => 'കേരളത്തിലെ ആദ്യത്തെ മെട്രോ റെയിൽ',
                'icon' => 'building',
            ],
            [
                'year' => '2018',
                'phase_ml' => 'കണ്ണൂർ വിമാനത്താവളം ഉദ്ഘാടനം',
                'phase_en' => 'Kannur Airport Opening',
                'desc_ml' => 'കണ്ണൂർ അന്താരാഷ്ട്ര വിമാനത്താവളം പണി പൂർത്തിയാക്കി ഉദ്ഘാടനം ചെയ്തു. ഉത്തര മലബാറിലെ ടൂറിസം മേഖലയ്ക്ക് വലിയ ഉണർവ്.',
                'desc_en' => 'Kannur International Airport completed and commercial flight operations inaugurated, boosting North Malabar tourism.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => '4th international airport in Kerala',
                'stats_ml' => 'കേരളത്തിലെ നാലാമത്തെ വിമാനത്താവളം',
                'icon' => 'award',
            ],
            [
                'year' => '2020',
                'phase_ml' => 'ഗെയിൽ പൈപ്പ്‌ലൈൻ പൂർത്തീകരണം',
                'phase_en' => 'GAIL Pipeline Completion',
                'desc_ml' => 'വെല്ലുവിളികൾ നിറഞ്ഞ കൊച്ചി-മംഗലാപുരം പ്രകൃതിവാതക പൈപ്പ്‌ലൈൻ വിജയകരമായി പൂർത്തിയാക്കി നാടിന് സമർപ്പിച്ചു.',
                'desc_en' => 'The challenging Kochi-Mangaluru natural gas pipeline successfully completed and dedicated, ensuring clean energy.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => '450 km pipeline completed',
                'stats_ml' => '450 കിലോമീറ്റർ പൈപ്പ്‌ലൈൻ',
                'icon' => 'building',
            ],
            [
                'year' => '2021',
                'phase_ml' => 'നവകേരള വീക്ഷണം',
                'phase_en' => 'Nava Kerala Vision',
                'desc_ml' => 'ദേശീയപാത വികസനം, കെ-ഫോൺ കണക്റ്റിവിറ്റി, പൊതുജനാരോഗ്യം എന്നിവ ലക്ഷ്യമാക്കി പുതിയ വികസന പത്രിക പ്രഖ്യാപിച്ചു.',
                'desc_en' => 'Next-gen development charter declared with focuses on NH widening, K-FON connectivity, and public health.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => '120+ projects layout prepared',
                'stats_ml' => '120+ പദ്ധതികളുടെ കരട് രേഖ',
                'icon' => 'landmark',
            ],
            [
                'year' => '2023',
                'phase_ml' => 'വാട്ടർ മെട്രോ ഉദ്ഘാടനം',
                'phase_en' => 'Water Metro Launch',
                'desc_ml' => 'കൊച്ചിയിലെ ദ്വീപുകളെ നഗരവുമായി ബന്ധിപ്പിക്കുന്ന ഏഷ്യയിലെ ആദ്യത്തെ ഇലക്ട്രിക് ഹൈബ്രിഡ് വാട്ടർ മെട്രോ സർവീസ് ആരംഭിച്ചു.',
                'desc_en' => 'Kochi Water Metro electric hybrid ferry services commercial operations launched, connecting Kochi islands.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => 'Asia\'s first integrated water metro',
                'stats_ml' => 'ഏഷ്യയിലെ ആദ്യ വാട്ടർ മെട്രോ',
                'icon' => 'hardhat',
            ],
            [
                'year' => '2024',
                'phase_ml' => 'വിഴിഞ്ഞം പരീക്ഷണ ഓട്ടം',
                'phase_en' => 'Vizhinjam Trial Run',
                'desc_ml' => 'വിഴിഞ്ഞം അന്താരാഷ്ട്ര ആഴക്കടൽ തുറമുഖത്തേക്ക് ആദ്യത്തെ വൻകിട് മദർഷിപ്പ് വിജയകരമായി അടുത്തു. ട്രയൽ റൺ വിജയകരം.',
                'desc_en' => 'Vizhinjam International Deepwater Seaport welcomed its first giant mothership, marking trial operations.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => 'Deepwater transshipment entry',
                'stats_ml' => 'ആദ്യത്തെ മദർഷിപ്പ് അടുത്തു',
                'icon' => 'building',
            ],
            [
                'year' => '2026',
                'phase_ml' => 'ദേശീയപാത & ഡിജിറ്റൽ സയൻസ് പാർക്ക്',
                'phase_en' => 'NH-66 & Digital Science Park',
                'desc_ml' => 'ദേശീയപാത 66-ന്റെ ആറുവരി വികസനം 95% പൂർത്തിയാകുകയും, തിരുവനന്തപുരം ഡിജിറ്റൽ സയൻസ് പാർക്ക് പൂർണ്ണമായി സജ്ജമാകുകയും ചെയ്തു.',
                'desc_en' => 'NH-66 six-lane upgrade completed to 95%, and Digital Science Park in Thiruvananthapuram enters full operations.',
                'government_en' => 'LDF Government (Pinarayi Vijayan)',
                'government_ml' => 'എൽ.ഡി.എഫ്. സർക്കാർ (പിണറായി വിജയൻ)',
                'stats_en' => '95% Highway Widening Completed',
                'stats_ml' => 'ദേശീയപാത വികസനം 95% പൂർത്തിയായി',
                'icon' => 'award',
            ],
        ];

        foreach ($milestones as $m) {
            TimelineMilestone::updateOrCreate(
                ['year' => $m['year'], 'phase_en' => $m['phase_en']],
                $m
            );
        }

        // 5. Seed Testimonials
        $testimonials = [
            [
                'name' => 'രാധാമണി അമ്മ',
                'role' => 'കുടുംബശ്രീ പ്രവർത്തക, കണ്ണൂർ',
                'quote_ml' => 'അടിസ്ഥാന സൗകര്യങ്ങൾ വികസിച്ചതോടെ ഞങ്ങളുടെ യാത്രാ ബുദ്ധിമുട്ടുകൾ ഇല്ലാതായി. ആശുപത്രിയിൽ വേഗത്തിലെത്താൻ ഇപ്പോൾ സാധിക്കുന്നുണ്ട്. ഇത് വെറും പ്രഖ്യാപനമല്ല, നേരിൽ കാണുന്ന മാറ്റമാണ്.',
                'quote_en' => 'With infrastructure development, our travel struggles are gone. We can reach the hospital quickly now. This is not just a promise; it\'s a visible change.',
                'rating' => 5,
                'avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
            ],
            [
                'name' => 'തോമസ് ജോസഫ്',
                'role' => 'ഐടി പ്രൊഫഷണൽ, തിരുവനന്തപുരം',
                'quote_ml' => 'ദേശീയപാത 6-വരിയാക്കിയതോടെ കൊച്ചിയിൽ നിന്ന് തിരുവനന്തപുരത്തേക്ക് ഉള്ള യാത്രാസമയം പകുതിയായി. പുതിയ സ്റ്റാർട്ടപ്പ് സംരംഭങ്ങൾക്ക് ഇത് പുതിയ വാതായനങ്ങൾ തുറക്കുന്നു.',
                'quote_en' => 'With the NH expanded to 6 lanes, the travel time from Kochi to Trivandrum has cut in half. This opens new gateways for technology startups.',
                'rating' => 5,
                'avatar' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80',
            ],
            [
                'name' => 'മുഹമ്മദ് അൻവർ',
                'role' => 'മത്സ്യത്തൊഴിലാളി, എറണാകുളം',
                'quote_ml' => 'വാട്ടർ മെട്രോ വന്നതോടെ ദ്വീപുകളിൽ നിന്നും നഗരത്തിലേക്ക് പോകാൻ ഇപ്പോൾ ബോട്ടുകൾക്ക് വേണ്ടി മണിക്കൂറുകളോളം കാത്തിരിക്കേണ്ടി വരുന്നില്ല. എസി ബോട്ടിൽ സുരക്ഷിതമായി പോവാം.',
                'quote_en' => 'Since the Water Metro started, we don\'t have to wait hours for ferries from the islands to the city. We can travel safely and comfortably in AC electric boats.',
                'rating' => 5,
                'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
            ],
        ];

        foreach ($testimonials as $t) {
            CitizenTestimonial::updateOrCreate(
                ['name' => $t['name'], 'role' => $t['role']],
                $t
            );
        }

        // 6. Seed KeralaStateInfo
        KeralaStateInfo::updateOrCreate(
            ['state_name' => 'Kerala'],
            [
                'formed_on' => '1956-11-01',
                'capital' => 'Thiruvananthapuram',
                'official_language' => 'Malayalam',
                'legislature' => 'Kerala Legislative Assembly',
                'high_court' => 'Kerala High Court',
                'current_governor' => 'Rajendra Arlekar',
                'first_cm' => 'E. M. S. Namboodiripad',
                'first_communist_cm_in_india' => 'E. M. S. Namboodiripad',
                'only_muslim_cm' => 'C. H. Mohammed Koya',
                'longest_serving_leaders' => ['K. Karunakaran', 'Pinarayi Vijayan'],
                'current_cm_name' => 'V. D. Satheesan',
                'current_cm_party' => 'Indian National Congress',
                'current_cm_alliance' => 'UDF',
                'current_cm_sworn_in' => '2026-05-18',
                'current_cm_status' => 'Current Chief Minister',
            ]
        );

        // 7. Seed ChiefMinisters
        $cms = [
            ['no' => 1, 'name' => 'E. M. S. Namboodiripad', 'party' => 'CPI', 'tenure' => '1957-1959'],
            ['no' => 2, 'name' => 'Pattom A. Thanu Pillai', 'party' => 'PSP', 'tenure' => '1960-1962'],
            ['no' => 3, 'name' => 'R. Sankar', 'party' => 'INC', 'tenure' => '1962-1964'],
            ['no' => 4, 'name' => 'E. M. S. Namboodiripad', 'party' => 'CPI(M)', 'tenure' => '1967-1969'],
            ['no' => 5, 'name' => 'C. Achutha Menon', 'party' => 'CPI', 'tenure' => '1969-1977'],
            ['no' => 6, 'name' => 'K. Karunakaran', 'party' => 'INC', 'tenure' => '1977'],
            ['no' => 7, 'name' => 'A. K. Antony', 'party' => 'INC', 'tenure' => '1977-1978'],
            ['no' => 8, 'name' => 'P. K. Vasudevan Nair', 'party' => 'CPI', 'tenure' => '1978-1979'],
            ['no' => 9, 'name' => 'C. H. Mohammed Koya', 'party' => 'IUML', 'tenure' => '1979'],
            ['no' => 10, 'name' => 'E. K. Nayanar', 'party' => 'CPI(M)', 'tenure' => '1980-1981'],
            ['no' => 11, 'name' => 'K. Karunakaran', 'party' => 'INC', 'tenure' => '1981-1982'],
            ['no' => 12, 'name' => 'A. K. Antony', 'party' => 'INC', 'tenure' => '1982-1987'],
            ['no' => 13, 'name' => 'E. K. Nayanar', 'party' => 'CPI(M)', 'tenure' => '1987-1991'],
            ['no' => 14, 'name' => 'K. Karunakaran', 'party' => 'INC', 'tenure' => '1991-1995'],
            ['no' => 15, 'name' => 'A. K. Antony', 'party' => 'INC', 'tenure' => '1995-1996'],
            ['no' => 16, 'name' => 'E. K. Nayanar', 'party' => 'CPI(M)', 'tenure' => '1996-2001'],
            ['no' => 17, 'name' => 'A. K. Antony', 'party' => 'INC', 'tenure' => '2001-2004'],
            ['no' => 18, 'name' => 'Oommen Chandy', 'party' => 'INC', 'tenure' => '2004-2006'],
            ['no' => 19, 'name' => 'V. S. Achuthanandan', 'party' => 'CPI(M)', 'tenure' => '2006-2011'],
            ['no' => 20, 'name' => 'Oommen Chandy', 'party' => 'INC', 'tenure' => '2011-2016'],
            ['no' => 21, 'name' => 'Pinarayi Vijayan', 'party' => 'CPI(M)', 'tenure' => '2016-2026'],
            ['no' => 22, 'name' => 'V. D. Satheesan', 'party' => 'INC', 'tenure' => '2026-Present'],
        ];

        foreach ($cms as $cm) {
            ChiefMinister::updateOrCreate(
                ['no' => $cm['no'], 'name' => $cm['name']],
                $cm
            );
        }
    }
}
